### ISSUE TITLE
Failed to walk through the tutorial at Mac

### ISSUE THREAD

**Issue by KillingJacky** [iamblue/ml-mt7687-config#2]
Did step by step as to the README file. But ./build.sh get error:

```
Generate feature.mk success!
Generate Makefile success!
Generate main.c success!
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open './sdk/project/mt7687_hdk/apps/iot_sdk/GCC/Makefile'
    at Error (native)
./build.sh: line 3: ./build.sh: No such file or directory
```

**Comment by iamblue** [comment]
hello @KillingJacky ~ Your SDK is 3.2.0? Microlattice is supporting SDK3.0.0 now. I will upgrade to 3.2.0 at next week :)

**Comment by KillingJacky** [comment]
No, my SDK version is 3.0.0. I will overtake the new version which supports 3.2.0 then. If the issue still exists, I will put some effort to figure it out why.

**Comment by iamblue** [comment]
Oh sorry ... README.md has some errors. you should use `npm run build` to build your microlattice app :).

## 完成環境安裝後，來啟動 Hello world 吧！
- 編輯 index.js 中的內容為下：

``` bash
print('Hello world!');
```
- 接下來，把 7687 與您的電腦連接，再輸入: `npm run build`
- 過一會即可以看到 Hello world !
- ps. 若出現一些錯誤請再做一次 `npm run build` 即可。

**Comment by iamblue** [comment]
https://preview.c9users.io/iamblue/test/

This is a test project run on c9s.io space, maybe you can reference this folder~
